/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dealer.deep;import cn.zhuatech.dealer.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                               */
@RestController @RequestMapping("/api/admin/dealer-ops") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                           */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/dealers/{id}/approve")ApiResponse<?> approve(@PathVariable Long id,@Valid @RequestBody DeepDomainService.ApprovalRequest r){return ApiResponse.ok(s.approve(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/orders/{id}/approve")ApiResponse<?> order(@PathVariable Long id){return ApiResponse.ok(s.approveOrder(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/rebates/{id}/settle")ApiResponse<?> settle(@PathVariable Long id,@Valid @RequestBody DeepDomainService.SettleRequest r){return ApiResponse.ok(s.settle(id,r));}}
