/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dealer.deep;import cn.zhuatech.dealer.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/dealer-ops") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                        */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/dealers")ApiResponse<?> dealer(@Valid @RequestBody DeepDomainService.DealerRequest r){return ApiResponse.ok(s.createDealer(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@PostMapping("/dealers/{id}/submit")ApiResponse<?> submit(@PathVariable Long id){return ApiResponse.ok(s.submit(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/dealers/{id}/authorizations")ApiResponse<?> authorize(@PathVariable Long id,@Valid @RequestBody DeepDomainService.AuthorizationRequest r){return ApiResponse.ok(s.authorize(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/orders")ApiResponse<?> order(@Valid @RequestBody DeepDomainService.OrderRequest r){return ApiResponse.ok(s.order(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/orders/{id}/fulfill")ApiResponse<?> fulfill(@PathVariable Long id){return ApiResponse.ok(s.fulfill(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/orders/{id}/rebates")ApiResponse<?> claim(@PathVariable Long id,@Valid @RequestBody DeepDomainService.RebateRequest r){return ApiResponse.ok(s.claim(id,r));}}
