/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dealer.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="dms_dealers",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","dealerCode"})) class DealerPartner{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String dealerCode;@Column(nullable=false,length=140)String name;@Column(nullable=false,length=40)String taxNo;@Column(nullable=false,length=20)String status="DRAFT";double creditLimit;double creditUsed;@Column(nullable=false,length=20)String riskLevel="NORMAL";LocalDate agreementEnd;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
protected DealerPartner(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
DealerPartner(String o,String c,String n,String t,LocalDate e){organizationCode=o;dealerCode=c;name=n;taxNo=t;agreementEnd=e;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="dms_authorizations",uniqueConstraints=@UniqueConstraint(columnNames={"dealerId","productCode","regionCode"})) class TerritoryAuthorization{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long dealerId;@Column(nullable=false,length=50)String productCode;@Column(nullable=false,length=50)String regionCode;double minimumUnitPrice;LocalDate validFrom;LocalDate validTo;@Column(nullable=false,length=20)String status="ACTIVE";/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
protected TerritoryAuthorization(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
TerritoryAuthorization(Long d,String p,String r,double m,LocalDate f,LocalDate t){dealerId=d;productCode=p;regionCode=r;minimumUnitPrice=m;validFrom=f;validTo=t;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="dms_channel_orders",uniqueConstraints=@UniqueConstraint(columnNames="orderNo")) class ChannelOrder{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false)Long dealerId;@Column(nullable=false,length=50)String orderNo;@Column(nullable=false,length=50)String productCode;@Column(nullable=false,length=50)String regionCode;int quantity;double unitPrice;double totalAmount;@Column(nullable=false,length=20)String status="PENDING_APPROVAL";LocalDate orderDate;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
protected ChannelOrder(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
ChannelOrder(Long d,String n,String p,String r,int q,double u,LocalDate date){dealerId=d;orderNo=n;productCode=p;regionCode=r;quantity=q;unitPrice=u;totalAmount=q*u;orderDate=date;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="dms_rebate_claims",uniqueConstraints=@UniqueConstraint(columnNames="claimNo")) class RebateClaim{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long orderId;@Column(nullable=false,length=50)String claimNo;double claimAmount;double approvedAmount;@Column(nullable=false,length=20)String status="SUBMITTED";LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                    */
protected RebateClaim(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                             */
RebateClaim(Long o,String n,double a){orderId=o;claimNo=n;claimAmount=a;createdAt=LocalDateTime.now();}}
